version: "3.2"
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  nginx:
    image: "xcgd/nginx-vts:1.16.1-0.1.18"
    ports:
      - "8080:80"
    volumes:
      - ./html/:/usr/share/nginx/html/ 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_log:/var/log/nginx/
    networks:
      monitoring:

  nginx_exporter:
    image: "sophos/nginx-vts-exporter:v0.10.6"
    depends_on: [nginx]
    ports:
      - "9913:9913"
    environment:
      - NGINX_STATUS=http://nginx/status/format/json
      - METRICS_ENDPOINT=/metrics
      - NGINX_RETRIES=10
      - METRICS_NS=otus_nginx
    networks:
      monitoring:

  nginx_log_exporter:
    image: "quay.io/martinhelmich/prometheus-nginxlog-exporter:v1.7.1"
    depends_on: [nginx]
    ports:
      - "9914:4040"
    environment:
      - namespace=nginxlogs
    volumes:
      - ./nginx_log:/mnt/nginxlogs
      - ./nginx_log/access.log3:/mnt/nginxlogs/access.log
      - ./config/nginxlog_exporter.yml:/etc/prometheus-nginxlog-exporter.yml
      
    command: -config-file /etc/prometheus-nginxlog-exporter.yml  
    networks:
      monitoring:

networks:
  monitoring:

