global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  - job_name: nginx_exporter
    static_configs:
    - targets: ['nginx_exporter:9913']

  - job_name: nginx_log_exporter
    static_configs:
    - targets: ['nginx_log_exporter:4040']

  - job_name: custom_exporter
    static_configs:
    - targets: ['192.168.1.50:8000']