phantom:
  address: nginx:80
  ssl: false
  load_profile:
    load_type: rps
    schedule: line(30, 200, 3m) const(300, 2m)
  ammofile: ammo.txt
  instances: 300

#autostop:
#  autostop:
#    - time(500, 60s)
#    - net(110, 75%, 100s)

telegraf:
  enabled: false
  config: monitoring.xml
  kill_old: false

overload:
  enabled: false
  job_name: POST requests
  job_dsc: line(1000, 205000, 5m) const(205000, 5m) | 100 instances | 2 cores
  token_file: token.txt