filebeat.inputs:

- type: log
  enabled: false
  paths:
    - /var/log/auth.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3




setup.kibana:
  host: "http://localhost:5601"
  username: "elastic"
  password: "changeme"

output.elasticsearch:
  hosts: ["192.168.1.50:9200"]
  username: "elastic"
  password: "changeme"